################################################
# Service: mydata
#################################################
apiVersion: v1
kind: Service
metadata:
 name: mydata
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: mydata
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mydata
  labels:
    account: mydata
